aws:
  region: "ap-southeast-1"
  secretStoreName: "costudy-aws-store"

secrets:
  awsPath: ""
  targetSecretName: "costudy-backend-secret"
  externalSecretName: "costudy-backend-external-secret"
  configMapName: "costudy-backend-configmap"

registry:
  secretName: gitlab-registry-secret
  awsPath: ""
  externalSecretName: "gitlab-registry-external-secret"

backend:
  name: costudy-backend
  replicaCount: 1
  revisionHistoryLimit: 2
  image:
    repository: registry.noseyug.online/costudy-group/costudy/costudy-be
    tag: ""
    pullPolicy: Always
  port: 3001
  service:
    name: costudy-backend-service
    type: ClusterIP
    port: 3001
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  probes:
    enabled: false
    startup:
      path: /api/rooms/public
      failureThreshold: 30
      periodSeconds: 10
    liveness:
      path: /api/rooms/public
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3
    readiness:
      path: /api/rooms/public
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
  config:
    PORT: "3001"
    NODE_ENV: "development"
    DB_HOST: "costudy-db.ct428ggiqqq8.ap-southeast-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_USER: "postgres"
    DB_NAME: "postgres"
    EMAIL_FROM: "Costudy <no-reply@noseyug.online>"

frontend:
  name: costudy-frontend
  replicaCount: 1
  revisionHistoryLimit: 2
  image:
    repository: registry.noseyug.online/costudy-group/costudy/costudy-fe
    tag: ""
    pullPolicy: Always
  port: 80
  service:
    name: costudy-frontend-service
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
  probes:
    enabled: false
    readiness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3

ingress:
  enabled: true
  name: costudy-ingress
  className: nginx
  host: ""
  tlsSecretName: letsencrypt-tls
  certManager:
    enabled: true
    issuerName: letsencrypt-dev
  proxyReadTimeout: "3600"
  proxySendTimeout: "3600"
  proxyBodySize: "50m"
  affinity: "cookie"
  session-cookie-name: "route"
  session-cookie-hash: "sha1"
