secrets:
  awsPath: "prod/costudy/backend"

registry:
  awsPath: "prod/costudy/registry"

backend:
  image:
    tag: "cf2e69d3"
  revisionHistoryLimit: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    enabled: true
  probes:
    enabled: true
  config:
    NODE_ENV: "production"

frontend:
  image:
    tag: "cf2e69d3"
  revisionHistoryLimit: 5
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  hpa:
    enabled: true
  probes:
    enabled: true

ingress:
  host: costudy-prod.noseyug.online
  certManager:
    issuerName: letsencrypt-prod
