apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.secrets.configMapName | default "costudy-be-config" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "costudy.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.backend.config | nindent 2 }}
