apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "costudy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  strategy:
    type: {{ .Values.frontend.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.secretName }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ include "costudy.fe.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
