apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "costudy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      protocol: TCP
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Values.frontend.name }}
