apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.awsPath }}
