apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.aws.secretStoreName | default "costudy-aws-store" }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }} #ap-southeast-1 # Thay bằng region của bạn
