apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecretName | default "backend-external-secret" }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName | default "costudy-aws-store" }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.targetSecretName | default "costudy-be-secret" }} # "costudy.be.fullname" . }}-secret  #costudy-be-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.awsPath }} #prod/costudy/backend
