apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.registry.externalSecretName | default "gitlab-registry-external-secret" }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName | default "costudy-aws-store" }}
    kind: SecretStore
  target:
    name: {{ .Values.registry.secretName }}
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"{{ `{{ .server | trim }}` }}":{"username":"{{ `{{ .user | trim }}` }}","password":"{{ `{{ .pass | trim }}` }}","auth":"{{ `{{ (printf "%s:%s" (.user | trim) (.pass | trim)) | b64enc }}` }}"}}}'
  data:
  - secretKey: user
    remoteRef:
      key: {{ .Values.registry.awsPath }}
      property: username
  - secretKey: pass
    remoteRef:
      key: {{ .Values.registry.awsPath }}
      property: password
  - secretKey: server
    remoteRef:
      key: {{ .Values.registry.awsPath }}
      property: server
